### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by remiminnebo** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#10]
Please provide the following information for your submission:

### What is your name? (First, Last)
Remi Minnebo

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/remiminnebo/tf-challenge-01
### What Challenge is this for? (Challenge number between 1 and 5)
1
### (Optional) Anything else we should know? e.g., language used, location, blog post?
Everything is handled by github actions. Secret for Azure SPN is stored within Github secrets.
The terraform configuration is deployed and then I use Azure login and Azure CLI steps to automate the CI/CD from my cloned azure-eats repo at: https://github.com/remiminnebo/azure-eats 
live website can be seen here: https://apps-rmi-tf-challenge-01-apps-s-rmi-tf-challenge-01.azurewebsites.net/ 

I have added the log from the github action in attachment. 

blog post:
http://hhmfumusdwvviwebsite.azurewebsites.net/2020/06/22/terraform-azure-challenge-1/

Cool challenge guys! Curious to see what's next.
[1_Terraform.txt](https://github.com/Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020/files/4815926/1_Terraform.txt)

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
