### ISSUE TITLE
[CHALLENGE SUBMISSION] OmegaMadLab - Challenge1

### ISSUE THREAD

**Issue by OmegaMadLab** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#11]
### What is your name? (First, Last)

Marco Obinu

### Where is your GitHub Repo ?(With your challenge solution)

https://github.com/OmegaMadLab/TerraformOnAzure-Challenge1

The deployed webapp is available at https://terraformonazure-app-service.azurewebsites.net/

### What Challenge is this for? (Challenge number between 1 and 5)

Challenge 1

### (Optional) Anything else we should know? e.g., language used, location, blog post?

Quite new to Terraform, I usually work with ARM templates. I used Terraform also for the CI configuration, executing an AZ CLI command via a local-exec.

Location: Arenzano, Genova, Italy
Blog post: I'll write something during next days, https://www.omegamadlab.com

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
