### ISSUE TITLE
[CHALLENGE SUBMISSION] 1 - Marc Duiker

### ISSUE THREAD

**Issue by marcduiker** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#17]
Please provide the following information for your submission:

### What is your name? (First, Last)
Marc Duiker

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/marcduiker/AzureEats-Website

### What Challenge is this for? (Challenge number between 1 and 5)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post?
~~Tried to setup a GitHub Action to do the Terraform deployment, but got stuck at `Terraform fmt - check`. Running the script manually worked fine.~~
I didn't know how to use the `fmt` argument properly. Thanks to @ntrogh it's working now! 😊

Still some issues with the dotnet publish step though.

```
react-scripts build
  
  Creating an optimized production build...
  
  Treating warnings as errors because process.env.CI = true.
  Most CI servers set it automatically.
  
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! app@0.1.0 build: `react-scripts build`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the app@0.1.0 build script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  Failed to compile.
```

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
