### ISSUE TITLE
[CHALLENGE SUBMISSION] Sergey .NET

### ISSUE THREAD

**Issue by smigalni** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#18]
Please provide the following information for your submission:

### What is your name? (First, Last)
Sergey Migalnikov

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/smigalni/AzureEats-Website

### What Challenge is this for? (Challenge number between 1 and 5)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post?
I have created Azure Web App (app service and app service plan) using Terraform. Scripts can be found here: https://github.com/smigalni/AzureEats-Website/tree/master/Terraform/WebApp.
Run terraform scripts from my PC. 
Link to the site: https://myverybestappservicename.azurewebsites.net/

Terraform is one of my favorite topics in my blog, take a look: https://sergeydotnet.com/tag/terraform/

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
