### ISSUE TITLE
[CHALLENGE SUBMISSION] Stijnc - Challenge 1

### ISSUE THREAD

**Issue by Stijnc** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#21]
Please provide the following information for your submission:

### What is your name? (First, Last)
Stijn Callebaut

### Where is your GitHub Repo ?(With your challenge solution)
[Stijnc/terraform-azure-hashiconf2020](https://github.com/Stijnc/terraform-azure-hashiconf2020/tree/11d8fb6eea0f97e44d3d3442940b8b95f89874e7)

### What Challenge is this for? (Challenge number between 1 and 5)
1
### (Optional) Anything else we should know? e.g., language used, location, blog post?
- tried to use github actions output to make the pipeline more dynamic but ...
- still struggling with Azure cli action and environment actions.

[EDIT] updated link to commit for challenge 1

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
