### ISSUE TITLE
[CHALLENGE SUBMISSION] jvhoof

### ISSUE THREAD

**Issue by jvhoof** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#22]
Please provide the following information for your submission:

### What is your name? (First, Last)
Joeri Van Hoof

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/jvhoof/AzureEats-Website

### What Challenge is this for? (Challenge number between 1 and 5)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Deploy on Azure Cloud Shell 
cd ~/clouddrive/ && wget -qO- https://github.com/jvhoof/AzureEats-Website/archive/master.zip | jar x && cd ~/clouddrive/AzureEats-Website-master/ && ./deploy.sh

Deploy on GitHub Actions using the workflow provided. Additional improvment could be to save state in Azure Storage Account or Terraform Cloud.

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
