### ISSUE TITLE
Links to 2 different sample apps for challenge 01

### ISSUE THREAD

**Issue by sdebruyn** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#3]
For the first challenge, the [readme](https://github.com/Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020/blob/main/challenges/challenge1/Readme.md) links to 2 different sample apps to fork:

- https://github.com/Terraform-On-Azure-Workshop/TailwindTraders-Website
- https://github.com/Terraform-On-Azure-Workshop/AzureEats-Website

**Comment by ntrogh** [comment]
Fixed!
