### ISSUE TITLE
[CHALLENGE SUBMISSION] Stijnc - Challenge 2

### ISSUE THREAD

**Issue by Stijnc** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#32]
Please provide the following information for your submission:

### What is your name? (First, Last)
Stijn Callebaut

### Where is your GitHub Repo ?(With your challenge solution)
[Stijnc/terraform-azure-hashiconf2020](https://github.com/Stijnc/terraform-azure-hashiconf2020/tree/d26c967b683eaefbcd0c5ffd2ddd9bf3824d43c4)

### What Challenge is this for? (Challenge number between 1 and 5)
2
### (Optional) Anything else we should know? e.g., language used, location, blog post?
- persistent storage not working with mongoDB and azure file shares
- Bitnami MongoDB used for non root container
- Should use keyvault for the connection strings

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
