### ISSUE TITLE
[CHALLENGE SUBMISSION]  3

### ISSUE THREAD

**Issue by matsest** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#38]
Please provide the following information for your submission:

### What is your name? (First, Last)

Mats, Estensen

### Where is your GitHub Repo ?(With your challenge solution)

https://github.com/matsest/AzureEats-Website

### What Challenge is this for? (Challenge number between 1 and 5)

3

### (Optional) Anything else we should know? e.g., language used, location, blog post?

- Already did this as part of challenge 01 :) Haven't run terraform locally as part of these challenges yet, besides what's run with the [pre-commit config](https://github.com/matsest/AzureEats-Website/blob/master/.pre-commit-config.yaml)
- Created a storage account in its own resource group
- Service principal created and given owner role on my subscription
- Keys and secret added as secrets to Github repo
- See backend configuration in [providers.tf](https://github.com/matsest/AzureEats-Website/blob/master/providers.tf)
- See github action configuration [here](https://github.com/matsest/AzureEats-Website/blob/master/.github/workflows/terraform_appservice.yaml)

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
