### ISSUE TITLE
[CHALLENGE SUBMISSION] sdebruyn challenge 01

### ISSUE THREAD

**Issue by sdebruyn** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#4]
Please provide the following information for your submission:

### What is your name? (First, Last)
Sam Debruyn

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/sdebruyn/Azure-Terraform-Challenge-01
live: https://tfazclsdb.azurewebsites.net/ (no always-on, you'll have to refresh a couple of times before it comes up)

### What Challenge is this for? (Challenge number between 1 and 5)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post?
There are some issues with the repo/instructions: https://github.com/Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020/issues?q=is%3Aissue+author%3Asdebruyn

**Comment by sdebruyn** [comment]
First this link pointed to https://github.com/sdebruyn/Azure-Terraform-Challenge-01-Tailwind-Traders
But then I changed it to the current one (because the link to the sample was also changed)

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
