### ISSUE TITLE
[CHALLENGE SUBMISSION]  Challenge 4 from Sergey .NET

### ISSUE THREAD

**Issue by smigalni** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#56]
Please provide the following information for your submission:

### What is your name? (First, Last)
Sergey Migalnikov

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/smigalni/AzureEats-Website-Challenge-4

### What Challenge is this for? (Challenge number between 1 and 5)
Challenge 4
### (Optional) Anything else we should know? e.g., language used, location, blog post?
Terraform scripts here: https://github.com/smigalni/AzureEats-Website-Challenge-4/tree/master/Terraform/AzureResources

Create docker image locally:
 docker-compose up

tag image
docker tag tailwindtraders/web:latest challenge4acrsergey.azurecr.io/tailwindtraders/web:0.1

push image to the Container registry
docker push challenge4acrsergey.azurecr.io/tailwindtraders/web:0.1

Helm files here: https://github.com/smigalni/AzureEats-Website-Challenge-4/tree/master/webfrontend

Helm command: helm install webfrontend webfrontend/

kubectl get service --watch
NAME          TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)        AGE
kubernetes    ClusterIP      10.0.0.1      <none>         443/TCP        90m
webfrontend   LoadBalancer   10.0.160.38   51.137.81.18   80:31849/TCP   2m17s
 
But could not connect to my application

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
