### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by matsest** [Terraform-On-Azure-Workshop/terraform-azure-hashiconf2020#7]
Please provide the following information for your submission:

### What is your name? (First, Last)

Mats, Estensen

### Where is your GitHub Repo ?(With your challenge solution)

https://github.com/matsest/AzureEats-Website

### What Challenge is this for? (Challenge number between 1 and 5)

1

Live web application here: https://mats-azureeats-website.azurewebsites.net/

### (Optional) Anything else we should know? e.g., language used, location, blog post?

- First time using Github Actions (normally use GitLab CI/CD) and azurerm as backend (normally use AWS s3). Tried using the official hashicorp/setup-terraform github action in combination with the existing action in the web app repo. Despite some lacking documentation I'm pretty satisifed with the result and will continue using GitHub Actions in the future! :)
- Location: Oslo, Norway
- Blog post: might come @ https://mxe.no

#### Notes

- The two build errors (see #2) for the application were fixed in https://github.com/matsest/AzureEats-Website/commit/66da496fa664e474797868a62ec31efb98d85b74, https://github.com/matsest/AzureEats-Website/commit/1e5f4cd60b069ec245aab984efd9a453eaec9433, https://github.com/matsest/AzureEats-Website/commit/b59e090856c5e18f1d7dc9d0f5771b4a16348e1c. Submitted a PR in https://github.com/Terraform-On-Azure-Workshop/AzureEats-Website/pull/3
- The free app service plan (F1) is [too small](https://github.com/matsest/AzureEats-Website/runs/796605506?check_suite_focus=true#step:9:16)?

**Comment by ntrogh** [comment]
Thanks for participating in the #TerraformOnAzure coding challenges!
We have attached your very special Astronaut Badger background, for you to use in all your upcoming video calls!

And to recognize you for your learning, you can collect your digital Azure Heroes badge on your mobile (you may need to install the Enjin wallet to collect it). Make sure to collect it today!
https://beam.enjin.io/claim/d32599695c8c28cfc24820492080fac0

Keep on learning and sharing!

Greetings from the #TerraformOnAzure team,
Suzanne, Floor, Erik & Nick

![TerraformOnAzure-Background-Final](https://user-images.githubusercontent.com/1908215/85914971-afcd2c00-b843-11ea-911f-d0bf83baace3.jpg)
